version: "3"
services:
  weatherapp2_backend:
    build:
      dockerfile: ./Dockerfile
      context: ./backend
    ports:
      - 9000:9000
    links:
      - weatherapp2_frontend
    environment:
      APPID: 99b1cb19e22ee4efa953441c7735e92b
    volumes:
      - ./backend:/usr/src/app
  weatherapp2_frontend:
    build:
      dockerfile: ./Dockerfile
      context: ./frontend
    ports:
      - 8000:8000
    volumes:
      - ./frontend:/usr/src/app
