version: "3"
services:
  weather_backend:
    build:
      dockerfile: ./Dockerfile
      context: ./backend
    ports:
      - 9000:9000
    links:
      - weather_frontend
    environment:
      APPID: 99b1cb19e22ee4efa953441c7735e92b
  weather_frontend:
    build:
      dockerfile: ./Dockerfile
      context: ./frontend
    ports:
